// generated by: https://www.typescriptlang.org/play

export class Reflector_IPC_main {
    static set options(arg: any);
    constructor(ipcMain: any);
    _msgcache: any;
    _ipcMain: any;
    _windows: Set<any>;
    handler_MQTT(msg: any): void;
    handler_ipc(event: any, msg: any): void;
    subscribe(): void;
    add_window(win: any): void;
    remove_window(win: any): void;
}
declare const l_: any;
export { l_ as l };
